default:
    image: python:3.7
    
stages: 
  - build
  - test
build:
  image: python:3.7
  stage: build
  script:
    - echo "Building..."
    - pip install pipenv
    - pipenv sync
    - pipenv run python replace_files.py
    - mkdir build
    - touch build/info.txt
  artifacts:
    paths: 
      - build/

test:
  image: python:3.7
  stage: test
  script:
    - echo "Testing..."
    - pip install pipenv
    - pipenv sync
    - pipenv run python replace_files.py
    - pipenv run nose2 -v
    - test -f "build/info.txt"
